### ISSUE TITLE
Empty body for post requests

### ISSUE THREAD

**Issue by rico** [pitwch/php-wrapper-proffix-restapi#5]
Hi, thanks for that really handy piece of software! I'm doing my first steps with the Proffix API V3.

If I do a `post` request, for example to create an `Adresse`, I get a `201` code but an empty body. Searching around in the response object, I have found a `Location` header which seems to be the url for the `get` request to get the created `Adresse`. Is this normal behaviour of the Proffix API or did I misunderstand something using your wrapper?

Thanks!

**Comment by rico** [comment]
... found it in the docs: 

> 

POST | Legt eine neue Ressource an | HTTP 201 (created) | Header "Location" beinhaltet URL auf die angelegte Ressource
-- | -- | -- | --

**Comment by pitw** [comment]
Antwort in Deutsch ;) 
Der Wrapper wurde lange Zeit nicht mehr aktualisiert, da wir eigentlich kein PHP mehr einsetzen.
Sollte aber +/- funktionieren.
Ansonsten wirf mal einen Blick in den [Wrapper für Golang](https://github.com/pitwch/go-wrapper-proffix-restapi) - der wird von uns produktiv eingesetzt, ist "battle-tested" und enthält viele hübsche Zusatzfunktionen.
F.ex. zu deinem obigen Beispiel: https://github.com/pitwch/go-wrapper-proffix-restapi/blob/20aaa86c79b17cd622d329b0c3b5eba375ee44b5/proffixrest/tools.go#L32

**Comment by rico** [comment]
... ach jetzt - aus der Schweiz, dann noch :-) Danke für die Antwort. 

> Der Wrapper wurde lange Zeit nicht mehr aktualisiert, da wir eigentlich kein PHP mehr einsetzen.
Sollte aber +/- funktionieren.

PHP Wrapper funktioniert eigentlich einwandfrei. 

> Ansonsten wirf mal einen Blick in den Wrapper für Golang - der wird von uns produktiv eingesetzt, ist "battle-tested" und enthält viele hübsche Zusatzfunktionen (ist eine andere Sprache aber der "Ablauf" ist derselbe...)

Go ist in diesem Projekt nicht wirklich eine Option, aber ich warte aber schon länger bis das hier etwas Fahrt aufnimmt: https://github.com/spiral/framework

> F.ex. zu deinem obigen Beispiel: https://github.com/pitwch/go-wrapper-proffix-restapi/blob/20aaa86c79b17cd622d329b0c3b5eba375ee44b5/proffixrest/tools.go#L32

... yep, habe ich natürlich in PHP genau so gemacht, als ich dem Hinweis in den Docs gefunden habe :-)
